[549] drag and drop resource from outside the engine
Unnamed-Company/LittleOrionEngine pull request #144
Opened 2020-05-26 17:23 UTC by yalania

https://app.hacknplan.com/p/113092/kanban?categoryId=0&boardId=315784&taskId=549&tabId=basicinfo

feature #119

2020-05-26 20:23 UTC, JorxSS approved these changes
I tried to crash it, and I couldn't. It works smooth, good job!

2020-05-26 21:08 UTC, Dartemiss requested changes
Very good job! I saw that if u drag multiple objects it imports multiple objects.
Just a thing, if the object that you drag isn't a file importable by the engine it crashes, i tried .obj and .zip and it crashed with both. It should log an error message but not crash!

2020-05-26 21:08 UTC, Dartemiss commented on Engine/Filesystem/Path.cpp
> +	free((void*)data.buffer);
Why do you change delete by free?

2020-05-26 21:08 UTC, Dartemiss commented on Engine/Module/ModuleResourceManager.h
> -	std::unique_ptr<ResourceDataBase> resource_DB = nullptr;
Why changing initialization to nullptr?

2020-05-28 15:50 UTC, yalania commented on Engine/Filesystem/Path.cpp
> +	free((void*)data.buffer);
because if the memory is allocated with a malloc you need to use free instead of delete[] that can have undefined behaviour

2020-05-28 15:50 UTC, yalania commented on Engine/Module/ModuleResourceManager.h
> -	std::unique_ptr<ResourceDataBase> resource_DB = nullptr;
because I discovered that smart pointers are initialized to nullptr by the default constructor so we don't need this.

2020-05-29 11:39 UTC, Dartemiss approved these changes
GJ, now don't crash, although i think a message on the console should be log in order to know that a file isn't importable.

2020-05-30 09:41 UTC, merged