Feature/movement
Unnamed-Company/LittleOrionEngine pull request #151
Opened 2020-05-29 14:02 UTC by marcorod94

- Now the movement game objects is done by the transform of it.
- Collision detection is still working with bullet.

2020-05-29 22:46 UTC, Dartemiss requested changes
There are a few things wrong
- Collision bugs that make you fly over a million meters [https://gyazo.com/45c83171cc2df49ad7f79bc92d6f04e5]
-Gravity is computed wrongly (plane velocity)
-Jump and double jump works bad  (it feels very weird and buggy)

I think that the approach that @mariofv said to @vidalmelero doing as Carlos recomended to us would be much better as we would have absolute control over the reaction of the player when colliding with a surface.

PD: Also I saw that if u disable physics from the collider the movement stops working, is that intended?

2020-05-29 22:46 UTC, Dartemiss commented on Engine/Component/ComponentCollider.cpp
> +
Here you are assuming that all colliders that are not mesh colliders are enemies, and that is a wrong assumption. For example skills like the light ball will have a sphere collider.

2020-05-29 22:46 UTC, Dartemiss commented on Engine/Component/ComponentCollider.cpp
> +	velocity.z = force.z;
This function is not an addforce, you are substituting a value by the parameter, for an add force it should be added.

2020-06-12 16:24 UTC, mariofv commented
Closing this because we have a new approach

2020-06-12 16:24 UTC, closed without merging