Feature undo redo
Unnamed-Company/LittleOrionEngine pull request #16
Opened 2020-02-19 12:23 UTC by Dartemiss

Refactor Undo/Redo:
- All logic moved to ModuleActions
- Now actions that adds/deletes gameobjects or components are serialized in memory and load, it is instantly

2020-02-19 16:11 UTC, mariofv requested changes
Great job, it now looks clearer :D Just change the naming as commented and it will be good to go

2020-02-19 16:11 UTC, mariofv commented on Engine/Actions/EditorActionSetTexture.h
> +	uint64_t UUID_COMP;
Naming should be `component_UUID` or `UUID_component` in order to match naming style.

2020-02-19 16:11 UTC, mariofv commented on Engine/Actions/EditorActionModifyLight.h
> +	uint64_t UUID_COMP;
Same as previous comment

2020-02-19 16:11 UTC, mariofv commented on Engine/Actions/EditorActionAddComponent.h
> +	uint64_t UUID_OWNER;
Same as previous comments 😄

2020-02-19 17:18 UTC, Dartemiss commented on Engine/Actions/EditorActionSetTexture.h
> +	uint64_t UUID_COMP;
Okay, I just have change it and pushed it. :D

2020-02-20 15:55 UTC, mariofv approved these changes

2020-02-23 11:11 UTC, yalania approved these changes
Looks good :) You can change most of the EditorAction's constructors to use member initialization if you want. It is really good explained here https://www.learncpp.com/cpp-tutorial/8-5a-constructor-member-initializer-lists/

2020-02-24 13:38 UTC, merged