Feature/ux
Unnamed-Company/LittleOrionEngine pull request #202
Opened 2020-06-26 17:23 UTC by yalania

- Now when creating a new material, state machine, skybox or folder a popup will appear aking for the name of the new file
- The same behaviour for renaming files
- Also small fix on scene so in case you try to load a scene that doesn't exists it will use the default one instead of crashing

2020-06-28 10:36 UTC, Dartemiss approved these changes
GJ Anabel. This will help a lot. Just a thing that doesn't work.

When renaming an STM and trying to place it on an object the name of the stm doesnt change. https://gyazo.com/2dad062c1d9d7861b1ffbfbd0860d261

2020-07-01 21:24 UTC, JorxSS requested changes
Code perfect, I even learned a new code things, thanks to you. But as I shared with you there are a few bugs that I think that would be better to be fixed before merge.

PD: Great Job btw, this will be so useful!

2020-07-02 18:02 UTC, JorxSS approved these changes

2020-07-02 18:02 UTC, JorxSS commented
Seal of approval inserted.

2020-07-02 18:13 UTC, merged