Fix/importing meshes
Unnamed-Company/LittleOrionEngine pull request #205
Opened 2020-07-01 08:02 UTC by JorxSS

Fixed bug:

* Now all the meshes have the current world position, not just 0,0,0.
* Also even if the mesh is called equal all of them are at their respective position

2020-07-01 08:03 UTC, yalania requested changes
I would like to have a look again to the skeleton importer, I changed it too fast and want to make sure it works for all models

2020-07-01 10:29 UTC, Dartemiss commented on Engine/ResourceManagement/Importer/ModelImporter.cpp
> +	App->filesystem->Save("/Hola.txt", config_to_serialize);
Hola.txt kill it

2020-07-01 11:07 UTC, Dartemiss commented on Engine/ResourceManagement/Importer/PrefabImporter.cpp
> +
Delete debug stuff

2020-07-01 11:07 UTC, Dartemiss approved these changes
All good mi pana

2020-07-02 17:29 UTC, yalania approved these changes
Test with mushdoom with good scale and also test the animation on the platform and if everything works I approve

2020-07-03 16:08 UTC, merged