Nav mesh for each scene
Unnamed-Company/LittleOrionEngine pull request #215
Opened 2020-07-06 14:06 UTC by JorxSS

WHAT'S HOT? (my body)

* Now we can have multiple navmeshes one from each scene

2020-07-06 14:53 UTC, Dartemiss commented on Engine/AI/NavMesh.cpp
> +void NavMesh::LoadNavMesh(const std::string nav_mesh_name)
Referece my pana

2020-07-06 14:54 UTC, Dartemiss commented on Engine/EditorUI/Panel/PanelNavMesh.h
> +#include "AI/NavMesh.h"
CS

2020-07-06 14:56 UTC, Dartemiss commented on Engine/Module/ModuleAI.cpp
> +void ModuleAI::SetNavMesh(const std::string nav_mesh_file)
Reference my friend

2020-07-06 15:05 UTC, Dartemiss requested changes
GJ!
But it doesn't work (crashes) when trying to bake a navmesh from a scene that is not saved or new.

2020-07-06 15:11 UTC, JoanStinson approved these changes
![1483897430_vR8qCsg png](https://user-images.githubusercontent.com/24247839/86609087-b712d900-bfab-11ea-81bd-4a99fc49e818.jpg)

2020-07-15 09:35 UTC, JorxSS commented
It will take more time so, I will re open this in the future

2020-07-15 09:35 UTC, closed without merging