Added sphere debug draw for enemy debugging
Unnamed-Company/LittleOrionEngine pull request #223
Opened 2020-07-09 16:40 UTC by JordiRomagosa

Added the sphere in the debug draw to debug enemy attacks and areas.

2020-07-09 16:59 UTC, mariofv requested changes

2020-07-09 16:59 UTC, mariofv commented on Engine/Module/ModuleDebugDraw.cpp
> +void ModuleDebugDraw::RenderShpere(const float3 & center, float radius, const float3 & color) const
Code Style, it should be
```
void ModuleDebugDraw::RenderShpere(const float3& center, float radius, const float3& color) const
```

2020-07-09 17:04 UTC, Dartemiss approved these changes
GJ, just code style that mario commented.

2020-07-10 08:10 UTC, JordiRomagosa commented
Style change modified.

2020-07-11 09:27 UTC, mariofv approved these changes

2020-07-11 16:38 UTC, merged