Feature/video player
Unnamed-Company/LittleOrionEngine pull request #250
Opened 2020-08-02 07:33 UTC by yalania

- Added "resource" video, is not real resource as it will stream directly from the file. For now the same video can't be play in different frames
- I fixed some warnings on the code that were annoying me
- I have do the extract data more generic, because we were creating a class for resources that doesn't need it

2020-08-09 23:36 UTC, mariofv reviewed
Work as expected. Few questions:
- Why is the functionality inside `ComponentImage`, and not in a new Component?
- Would it be possible to also include Audio without puting a SoundBank?

2020-08-10 05:35 UTC, yalania commented
I create a new computer ment at the beginning but I was just duplicating code from component image, at then a video is just a set of images changes. 

Opencv, the library I used is only for images it doesn't manage sound, so is not possible to do it.

2020-08-10 09:09 UTC, mariofv commented
> I create a new computer ment at the beginning but I was just duplicating code from component image, at then a video is just a set of images changes.

So then, could it be possible to add the sound resource of the video inside the component? This way everything would be more organized, and then maybe I would have sense to create a new component with the video resource + sound

2020-08-10 13:48 UTC, yalania commented
You don't let me be lazy :( Ok I will do it

2020-08-13 16:33 UTC, mariofv commented
Code looks ok, but I cannot try this until you merge develop :P

2020-08-21 15:30 UTC, mariofv requested changes
SetAspectRatio is not working for both `ComponentImage` and `ComponentVideo`, also look at the coment. Rest is fine, good job!

2020-08-21 15:30 UTC, mariofv commented on Engine/EditorUI/Panel/InspectorSubpanel/PanelComponent.cpp
> +
You forgot here to show the `CommonComponentWindow`, and this causes the Component Ui to show without the "Header":
![image](https://user-images.githubusercontent.com/17348688/90906980-ae972600-e3d2-11ea-98d7-52a19611374c.png)

2020-08-26 15:06 UTC, yalania commented
Aspect ratio is not working in master either

2020-08-28 10:14 UTC, mariofv approved these changes

2020-09-04 15:14 UTC, JorxSS approved these changes
Sorry for the delay, but hopefully you will pardon me because ...
![image](https://user-images.githubusercontent.com/49075678/92255020-0a34d980-eed2-11ea-889b-5fe77e3bde47.png)

Good Job Anabel!

2020-09-05 07:09 UTC, merged