Feature/3d audio
Unnamed-Company/LittleOrionEngine pull request #253
Opened 2020-08-07 19:05 UTC by RickyVimon

This PR needs the /audio version of the Gameplay Systems

2020-08-09 23:26 UTC, mariofv requested changes
This is not working for some banks like combat. Look at the comments and just two things:
- I couldn't load the engine at first because I needed to reimport `Library`. When this happens please increase the `Importer` variable `IMPORTER_VERSION` by one to force importing.
- Becareful when using `File` method `Load()`, because you have to free the used memory

2020-08-09 23:26 UTC, mariofv commented on Engine/ResourceManagement/Importer/SoundImporter.cpp
>  	}
Code style, { goes in a new line

2020-08-09 23:26 UTC, mariofv commented on Engine/ResourceManagement/Manager/SoundManager.cpp
> +#include "ResourceManagement/Metafile/MetafileManager.h"
Code style, includes should be sorted alphabetically

2020-08-09 23:26 UTC, mariofv commented on Engine/ResourceManagement/Resources/SoundBank.cpp
>  		RESOURCES_LOG_ERROR("Unable to load the sound_bank");
Why having two constructors that do almost the same stuff?

2020-08-09 23:26 UTC, mariofv commented on Engine/EditorUI/Panel/InspectorSubpanel/PanelComponent.cpp
> +				}
This check should be inside the `ComponentAudioSource`. Instead of comparing `event_name`, comapre selected event.

2020-08-09 23:26 UTC, mariofv commented on Engine/Component/ComponentAudioSource.h
> +	std::string selected_event;
Store it as an index to the events array, it's more efficient and this way we ensure that the selected event exists.

2020-08-09 23:26 UTC, mariofv commented on Engine/ResourceManagement/Importer/SoundImporter.cpp
> +	file_data.assign(static_cast <const char*> (file_imported_data.buffer), file_imported_data.size);
`file_imported_data` is copied to the `std::string` `file_data`, and then it's not used anymore. The thing is that the data aquired using `File` method `Load()` should be freed after usage, so there is a memory leak here.

2020-08-09 23:26 UTC, mariofv commented on Engine/ResourceManagement/Manager/SoundManager.cpp
> +	FileData exported_file_data = resource_exported_file_path->GetFile()->Load();
Same as previous comment, memory leak here

2020-09-06 16:10 UTC, Dartemiss commented on Engine/Component/ComponentAudioSource.cpp
> +	}
This method should be const!

2020-09-06 16:14 UTC, Dartemiss approved these changes
GJ man! I would suggest a StopEvent button if possible on the audio sorce UI because when pressing more than one event sometimes we don't want sound to overlap.

And pls fix the commented stuff :D

2020-09-07 09:01 UTC, mariofv approved these changes
Looks ok, just look at the comment of @Dartemiss and mine :)

2020-09-07 09:01 UTC, mariofv commented on Engine/EditorUI/Panel/InspectorSubpanel/PanelComponent.cpp
> +				}
Here I would do two things:
- Don't letting the user to play the event is "null". So, changing the order of ifs statements.
- Instead of comparing the name with  `"-"`, having a method in `ComponentAudioSource` that returns `true` or `false` depending on the `selected_event_index`, that would be cleaner

2020-09-07 11:31 UTC, merged