Feature/trails
Unnamed-Company/LittleOrionEngine pull request #269
Opened 2020-09-13 11:33 UTC by Misarte

2020-09-13 15:15 UTC, mariofv requested changes
In terms of usability, the inspector UI looks weird
![image](https://user-images.githubusercontent.com/17348688/93021676-465bee80-f5e4-11ea-9a07-5b1801760c64.png)
- The active, delete, copy and paste options are before the collapsing header.
- Tile rows and Tile columns shouldn't be shown if the texture mode is not tiled.
- Also the guizmos for changing floats are not usable, use `Imgui::DragFloat` instead.

In terms of funcionality:
- The variable distance now doesn't do anything.
- Width scaling has changed and existing trails look too big. Also changing the width by 0.1 makes the trail to big

Rest works amazing!

2020-09-13 15:15 UTC, mariofv commented on Engine/Component/ComponentTrail.cpp
> +			if (App->cameras->scene_camera)
I dont' understand this if condition, as it will always be true

2020-09-13 15:15 UTC, mariofv commented on Engine/Component/ComponentTrail.h
> +		REPEATPERSEGMENT
Code style, this should be named `REPEAT_PER_SEGMENT`

2020-09-13 15:15 UTC, mariofv commented on Engine/Component/ComponentTrail.h
> +	void CalculateCatmull(Spline& path_to_smoothen, std::vector<float3>& spline_points);
path_to_smoothen probably can be const, as well the whole method

2020-09-13 15:15 UTC, mariofv commented on Engine/Component/ComponentTrail.h
> +	float4 color = { 1.0f, 1.0f, 1.0f, 1.0f };
This can be rewritten into `float4 color = float4::one`

2020-09-13 19:55 UTC, Misarte commented
@mariofv  
- The width looks okay at 0.1 for me. 
- Also the distance does not do much because we so or so add extra points to smooth'en it, but i'll check it tomorrow.
- All the rest is fixed. I have committed the changes.
- Also tomorrow I'll check the color alpha fade over time.

2020-09-18 09:59 UTC, Misarte commented
Hello reviewers xD,

I have pushed some new code regarding the 3rd option (from Carlos lecture) of implementing the 1st and last point of the curve using the reflection formula. Please review and let me know so we can move on a merge.

@mariofv the color is bit more complicated than we thought, as it can not be assigned to each point (like in particles) and so the color interpolation results in flickering of 2 colors on the overall texture, so I would need to do it through shader.

2020-09-21 08:08 UTC, Misarte commented
Issues have been fixed! Please approve xD

2020-09-21 12:18 UTC, mariofv requested changes
Great job! Few things: 
- I still have some issues with the width, at the moment, is a bit difficult to tweak it easily in the inspector, because a change of just 0.1 makes a huge difference in the rendering. What you can do to solve this is to modify the `DragFloat` speed parameter. 
- The width of some trails in the scene is 1, so they look huge because of this. You have to create a new branch in the other repo adjusting existing trails before merging this.
- The minum distance parameter has no use.
- This branch is not up to develop and I cannot try it in game

2020-09-21 12:18 UTC, mariofv commented on Engine/Component/ComponentTrail.cpp
> +	unsigned int j = 0;
This variable is not used at all

2020-09-22 19:16 UTC, Dartemiss approved these changes
LGTM!

2020-09-22 19:18 UTC, mariofv approved these changes
Great job!

2020-09-22 19:18 UTC, merged