Reflections
Unnamed-Company/LittleOrionEngine pull request #287
Opened 2020-10-07 18:51 UTC by yalania

- Added SSR (screen space reflections) to have some reflections, they are not mirror like reflections and so they are not perfect, there are som value we can tweak
- Added skybox reflections

2020-10-09 22:45 UTC, mariofv reviewed
Scene window doesn't render

2020-10-11 14:42 UTC, raulgonzalezupc requested changes
It's kind of working as you said, there are a lot to improve, but if you make the changes requested I will aproved, I already tested but it feels kind of weird, and for our game I don't think the water will be super reflective since we have a cartoonish style. But pretty good job as allways ^^

2020-10-11 14:42 UTC, raulgonzalezupc commented on Game/Resources/Shaders/Lit/blinn_phong.fs
> +layout (location = 4) out vec4 ssrValuesBuffer;
Can you put this variables on CamelCase like the others to be consistent please? ^^

2020-10-11 14:42 UTC, raulgonzalezupc commented on Game/Resources/Shaders/Lit/blinn_phong.fs
> +	result +=texture(skybox_texture, R).rgb* 0.5;
you are adding the skybox texture allways without having in consideration if it is ocluded by another object.

2020-10-11 14:42 UTC, raulgonzalezupc commented on Game/Resources/Shaders/Lit/blinn_phong.fs
> +	result +=texture(skybox_texture, R).rgb* 0.5;
there should be and option to not have reflections of the skybox at all in my opinion, or at least be able to tweak the value of 0.5

2020-10-11 19:59 UTC, raulgonzalezupc commented
You have to change the code style of the layouts of the blinn still but I aprove it

2020-10-11 19:59 UTC, raulgonzalezupc approved these changes

2020-10-16 18:01 UTC, mariofv approved these changes
Water looks like water now, 10/10

2020-10-16 18:41 UTC, merged