Feature ai recast implementation
Unnamed-Company/LittleOrionEngine pull request #37
Opened 2020-03-14 19:57 UTC by Dartemiss

What's new?
- recast library addition and integration
- ModuleAI added to handle all AI
- NavMesh added to compute navigable mesh from rasterizing all scene triangles as input, to know which areas are walkable.
- A panel navmesh to bake a customized navmesh by changing parameters for the agent.
- Pathfinding in two modes: follow and straight, this feature is done by by chosing two raycasted points in the panel navmesh
- Serialize into a binary file (.bin) the navmesh, save/load at the begining of the scene (in the future it will be a resource)
- Debugdraw navmesh

2020-03-15 21:08 UTC, Pacasasgar approved these changes
Big PR indeed! For me all it's fine.

Very nice job :D

2020-03-17 01:50 UTC, mariofv requested changes
Great job, it looks really cool! Keep it going 💪

2020-03-17 01:50 UTC, mariofv commented on Engine/AI/DebugDrawGL.cpp
> +void DebugDrawGL::Begin(DuDebugDrawPrimitives prim, float size)
This comments goes for the whole file.

Because we are not using lots of this functions we should keep this class as short and clean as posible.

2020-03-17 01:50 UTC, mariofv commented on Engine/AI/GLCheckerTexture.h
> +#ifndef _GLCheckerTexture_H_
This class is not used at all, so it should be deleted.

2020-03-17 01:50 UTC, mariofv commented on Engine/AI/NavMesh.h
> +static const int MAX_SMOOTH = 2048;
This should be inside `NavMesh` definition in order to not contaminate the global context.

2020-03-17 01:50 UTC, mariofv commented on Engine/AI/NavMesh.h
> +	}
If this definition it's not strictly necessary, this function should be defined inside `.cpp` file.

2020-03-17 01:50 UTC, mariofv commented on Engine/AI/SampleDebugDraw.h
> +#ifndef _SampleDebugDraw_H_
This class is unfiltered, check that out.

2020-03-17 01:50 UTC, mariofv commented on Engine/Component/ComponentCamera.cpp
> +	App->artificial_intelligence->RenderNavMesh(*App->cameras->scene_camera);
This should be drawm in `ModuleDebugDraw` in order to keep responsabilities isolated in classes.

2020-03-17 01:50 UTC, mariofv commented on Engine/Module/ModuleAI.h
> +#include "AI/NavMesh.h"
Do I need to tell you what is wrong here? :)

2020-03-17 01:50 UTC, mariofv commented on Engine/Module/ModuleAI.h
> +	NavMesh nav_mesh = NavMesh();
This is unnecessary, because class constructor calls default constructors if not specified.

2020-03-17 01:50 UTC, mariofv commented on Engine/Module/ModuleEditor.h
> +	float3 selected_position = float3(0.0f, 0.0f, 0.0f);
Because this is a debug variable, it should be deleted now that we have scripting

2020-03-17 01:50 UTC, mariofv commented on Engine/Module/ModuleRender.cpp
> +bool ModuleRender::GetRayCastIntersectedPosition(const LineSegment & ray, float3& position)
You can avoid this function using `Triangle::Intersects()` `intersectionPoint` parameter. For that you can use current Mouse piciking redifining the function `GetRaycastIntertectedObject` of `ModuleRender`.

2020-03-17 17:49 UTC, Dartemiss commented
@mariofv I've done all the changes you suggested except deleting the debuging variable, because it could still be useful :D

2020-03-18 00:52 UTC, mariofv approved these changes

2020-03-19 02:23 UTC, merged